//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBESearchAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCode
    {
        public ItemCode()
        {
            this.CompanyItemCodes = new HashSet<CompanyItemCode>();
        }
    
        public int ItemCode1 { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CompanyItemCode> CompanyItemCodes { get; set; }
    }
}
