//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBESearchAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEDirectoryEntities1 : DbContext
    {
        public DBEDirectoryEntities1()
            : base("name=DBEDirectoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompanyItemCode> CompanyItemCodes { get; set; }
        public DbSet<CompanyNAICSCode> CompanyNAICSCodes { get; set; }
        public DbSet<DBECompany> DBECompanies { get; set; }
        public DbSet<ItemCode> ItemCodes { get; set; }
        public DbSet<NAICSCode> NAICSCodes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
